version: '3.9'

services:
  server:
    image: py-server
    restart: on-failure:5
    environment:
      SERVER_PORT: "${SERVER_PORT}"
    build:
        context: ./server

  client:
    image: go-client
    restart: on-failure:5
    depends_on:
      - server
    environment:
      SERVER_HOST: "${SERVER_HOST}"
      SERVER_PORT: "${SERVER_PORT}"
    build:
        context: ./client
        dockerfile: multistage.Dockerfile


